In [3]:
import numpy as np 
import scipy.stats
import pandas
import scipy.optimize as optimize
import random
from sklearn.datasets import make_sparse_spd_matrix
from sklearn.covariance import empirical_covariance, graphical_lasso


csvFile = pandas.read_csv('C:/Users/20254817/Desktop/Githib/Dependence-modeling-/data/student_exam_scores.csv')



data = csvFile.to_numpy()
data = data[: , np.arange(1,6)]
emp_cov = empirical_covariance(data)
#print(emp_cov)

precision_mat = np.linalg.inv(emp_cov)
#print(precision_mat)

cov_, precision_, costs_ , n_iter_ = graphical_lasso(emp_cov, alpha=10 , return_costs = True , return_n_iter = True)

abs_value = np.absolute(precision_)



#print("Estimated covariance matrix:\n", cov_)
print("\nEstimated precision matrix:\n", precision_)
print("\nEstimated cost:\n", costs_)
#print("\nnumber of iterations:\n", n_iter_)




Estimated precision matrix:
 [[ 0.10735462 -0.          0.          0.         -0.01623187]
 [-0.          0.44838706 -0.          0.         -0.        ]
 [ 0.         -0.          0.00502398 -0.         -0.00128466]
 [ 0.          0.         -0.          0.00461959 -0.0035874 ]
 [-0.01623187 -0.         -0.00128466 -0.0035874   0.02737052]]

Estimated cost:
 [(np.float64(40.92657566591667), np.float64(0.2380212815236924)), (np.float64(40.90922621610109), np.float64(-2.53886531798031e-08))]


In [8]:
d = 5
def construct_symmetric_matrix(Theta):
    Theta_matrix = np.zeros((d , d))
    upper_idx = np.triu_indices(d)
    Theta_matrix[upper_idx] = Theta
    Theta_matrix = Theta_matrix + Theta_matrix.T - np.diag(np.diag(Theta_matrix)) 
    return(Theta_matrix)

def pen_log_likelihood(Theta , EstimSigma , Lambda) :
    Theta_matrix  = construct_symmetric_matrix(Theta)
    abs_val_Theta_matrix = np.absolute(Theta_matrix)
    upper_idx = np.triu_indices(d)
    upper_triangle_abs_val_Theta_matrix =  abs_val_Theta_matrix[upper_idx]
    off_diag_sum = upper_triangle_abs_val_Theta_matrix.sum() - abs_val_Theta_matrix.trace()
    print("This is is the off diagonal sum:", off_diag_sum)
    det_Theta = np.linalg.det(Theta_matrix) 
    if det_Theta <= 0 :
        return -np.inf
    product_STheta = np.matmul(EstimSigma, Theta_matrix)
    trace_STheta =  product_STheta.trace()
    return(np.log(det_Theta) - trace_STheta - Lambda * off_diag_sum )

    
#A = np.random.randn(d, d)
#nitial_Theta_matrix = np.dot(A, A.T) + d * np.eye(d) 

# Convert to upper-triangular vector form
#upper_idx = np.triu_indices(d)
#initial_guess = initial_Theta_matrix [upper_idx]
#Lambda = 10
#random.seed(7)
#result = optimize.minimize(lambda x: -log_likelihood(x , emp_cov , Lambda) , np.array(initial_guess) ).x
#mle =  construct_symmetric_matrix(result)
#print("The maximum likelihood estimator of the precision matrix is given by \n", mle)    

In [9]:

upper_idx = np.triu_indices(d)
theta_matrix =  precision_[upper_idx]

cost = pen_log_likelihood(theta_matrix , emp_cov , 10)
print("This is the cost", cost)

This is is the off diagonal sum: 0.02110393142685707
This is the cost -22.319416237739066


In [9]:
real_cov = np.array([[.8, .3],
                     [.3, .4]])
rng = np.random.RandomState(0)
X = rng.multivariate_normal(mean=[0, 0],
                            cov=real_cov,
                            size=500)

In [10]:
X.shape

(500, 2)