In [2]:
import pandas as pd
import numpy as np 

Consider the square cyclic graph 1--2--3--4--1. A precision matrix that satisfies this structure is given by

In [29]:
d = 4
Theta = np.matrix([
[10 , 0.5  , 0 , 0.5],
[0.5 , 10 , 0.5 , 0 ],
[0 , 0.5 , 10 , 0.5],
[0.5 , 0 , 0.5 , 10]
])

print("This is the true precision matrix  \n", Theta)

This is the true precision matrix  
 [[10.   0.5  0.   0.5]
 [ 0.5 10.   0.5  0. ]
 [ 0.   0.5 10.   0.5]
 [ 0.5  0.   0.5 10. ]]


In [30]:
Sigma = np.linalg.inv(Theta) 
print("This is the true covariance matrix  \n", Sigma)

This is the true covariance matrix  
 [[10.   0.5  0.   0.5]
 [ 0.5 10.   0.5  0. ]
 [ 0.   0.5 10.   0.5]
 [ 0.5  0.   0.5 10. ]]


We first generate a sample of size $N=1000$ from a centered multivariate Guassian distribution with covariance matrix $\Sigma$

In [35]:
N = 10000
d = 4
mean = np.zeros(4)
X = np.random.multivariate_normal(mean ,Sigma , N)
X = np.transpose(X)
print(X)
####To calculate the covariance matrix using np.cov, we need to reshape X into a matrix where each row represnets a variable and each column a single observation
X.shape

[[-0.52441592 -0.05877654  0.03078628 ... -0.15875373  0.34668752
   0.24481908]
 [ 0.21657706  0.14533191  0.46972122 ... -0.43087671 -0.07993995
  -0.10462946]
 [ 0.14771453  0.49027769 -0.27289917 ... -0.41131446 -0.05042665
   0.24492077]
 [ 0.16309342  0.49179676  0.20675628 ... -0.19778069 -0.08560613
   0.5211206 ]]


(4, 10000)

In [36]:
EstimSigma = np.cov(X)
EstimTheta =  np.linalg.inv(EstimSigma)
print("This is the sample covariance matrix is  \n", EstimSigma)
print("This is the estimated precision matrix is  \n", EstimTheta)

This is the sample covariance matrix is  
 [[ 0.09941725 -0.00470907  0.00085346 -0.00690352]
 [-0.00470907  0.09856747 -0.0069519   0.00084826]
 [ 0.00085346 -0.0069519   0.10262244 -0.00479107]
 [-0.00690352  0.00084826 -0.00479107  0.10122533]]
This is the estimated precision matrix is  
 [[10.12898866  0.47660502 -0.01993087  0.6858553 ]
 [ 0.47660502 10.21674883  0.68718311 -0.02058601]
 [-0.01993087  0.68718311  9.81252525  0.45731635]
 [ 0.6858553  -0.02058601  0.45731635  9.94754305]]
