In [2]:
import pandas as pd
import numpy as np 

Consider the square cyclic graph 1--2--3--4--1. A precision matrix that satisfies this structure is given by

We first import data  

In [29]:
d = 4
Theta = np.matrix([
[10 , 0.5  , 0 , 0.5],
[0.5 , 10 , 0.5 , 0 ],
[0 , 0.5 , 10 , 0.5],
[0.5 , 0 , 0.5 , 10]
])

print("This is the true precision matrix  \n", Theta)

This is the true precision matrix  
 [[10.   0.5  0.   0.5]
 [ 0.5 10.   0.5  0. ]
 [ 0.   0.5 10.   0.5]
 [ 0.5  0.   0.5 10. ]]


We transform df to numpy for easy manipulations and then compute the covariance matrix 

We transform df to numpy for easy manipulations and then compute the covariance matrix 

In [30]:
Sigma = np.linalg.inv(Theta) 
print("This is the true covariance matrix  \n", Sigma)

This is the true covariance matrix  
 [[10.   0.5  0.   0.5]
 [ 0.5 10.   0.5  0. ]
 [ 0.   0.5 10.   0.5]
 [ 0.5  0.   0.5 10. ]]


We generate a sample pf size $N = 1000$ from a centered Guassian distribution with covariance matrix $\Sigma$ 

We first generate a sample of size $N=1000$ from a centered multivariate Guassian distribution with covariance matrix $\Sigma$

In [38]:
N = 10000
d = 4
mean = np.zeros(4)
X = np.random.multivariate_normal(mean ,Sigma , N)
print(X)
X.shape

[[-0.04231963  0.32991875 -0.07002136  0.28658341]
 [ 0.02595677  0.07487018 -0.04334342 -0.40979325]
 [-0.01492751  0.12558061  0.07797677 -0.12637802]
 ...
 [ 0.29997606  0.07924742 -0.13101757 -0.44451623]
 [ 0.60564868  0.1975385   0.0474323   0.01575487]
 [-0.06474599 -0.28034207  0.07689355 -0.34779462]]


(10000, 4)

Estimation by the inverse of the sample covariance matrix

In [36]:
####To calculate the covariance matrix using np.cov, we need to reshape X into a matrix where each row represnets a variable and each column a single observation
copyX = np.transpose(X)
EstimSigma = np.cov(copyX)
EstimTheta =  np.linalg.inv(EstimSigma)
print("This is the sample covariance matrix is  \n", EstimSigma)
print("This is the estimated precision matrix is  \n", EstimTheta)

This is the sample covariance matrix is  
 [[ 0.09941725 -0.00470907  0.00085346 -0.00690352]
 [-0.00470907  0.09856747 -0.0069519   0.00084826]
 [ 0.00085346 -0.0069519   0.10262244 -0.00479107]
 [-0.00690352  0.00084826 -0.00479107  0.10122533]]
This is the estimated precision matrix is  
 [[10.12898866  0.47660502 -0.01993087  0.6858553 ]
 [ 0.47660502 10.21674883  0.68718311 -0.02058601]
 [-0.01993087  0.68718311  9.81252525  0.45731635]
 [ 0.6858553  -0.02058601  0.45731635  9.94754305]]


In [37]:
from sklearn.covariance import EmpiricalCovariance