# Graphical Lasso 

This notebook performs the graphical Lasso on a 4‑dimensional Gaussian random vector whose precision matrix corresponds to the cyclic graph 1–2–3–4–1. This is done using the function \texttt{graphical_lasso()} from the \texttt{sklearn.covariance package}. 

## 1. Define the graph and precision matrix

In [63]:
import numpy as np
import pandas as pd

d = 4
Theta = np.array([
    [10,  5,  0, 3],
    [ 5, 10,  5,  0],
    [ 0,  5, 10 ,   5],
    [ 3,  0,  5, 10]
])
Sigma = np.linalg.inv(Theta)

## 2. Simulate Gaussian sample

In [64]:
N = 10**6
mean = np.zeros(d)
X = np.random.multivariate_normal(mean, Sigma, size=N)
X[:5]

array([[ 0.18846935, -0.84386078,  0.59970319, -0.25219988],
       [ 0.7388085 , -0.32582239,  0.24215606, -0.2507643 ],
       [-0.65637362,  0.70860511, -1.2946282 ,  0.93780815],
       [-0.07701061,  0.31825742,  0.39118278, -0.24349002],
       [ 1.26770721, -1.16182284,  1.16278316, -0.60700645]])

In [65]:
EstimSigma = np.cov(X, rowvar=False)
EstimSigma

array([[ 0.29380058, -0.264345  ,  0.23507001, -0.20588586],
       [-0.264345  ,  0.38816912, -0.31161651,  0.23543032],
       [ 0.23507001, -0.31161651,  0.38791333, -0.26473108],
       [-0.20588586,  0.23543032, -0.26473108,  0.29415713]])

In [66]:
from sklearn.covariance import  graphical_lasso

covariance , precision = graphical_lasso(Sigma , alpha=0.21)

print("Precision matrix (Theta):\n", precision)
print("Covariance matrix (Sigma):\n", covariance)

Precision matrix (Theta):
 [[ 3.49556036  0.46479537 -0.10590815  0.        ]
 [ 0.46479537  2.83080032  0.69680704 -0.10591083]
 [-0.10590815  0.69680704  2.83079946  0.46479473]
 [ 0.         -0.10591083  0.46479473  3.49556015]]
Covariance matrix (Sigma):
 [[ 0.29411765 -0.05470587  0.0252941  -0.0050208 ]
 [-0.05470587  0.38823529 -0.10176471  0.02529438]
 [ 0.0252941  -0.10176471  0.38823529 -0.05470588]
 [-0.0050208   0.02529438 -0.05470588  0.29411765]]
